service: thumbnail-generator

frameworkVersion: '3'

provider:
  name: aws
  runtime: java17
  stage: prod
  region: us-east-1

custom:
  serviceName: ${self:service}
  imagesS3Bucket: vinziev-thumbnail-generator-images

package:
  artifact: target/thumbnail-generator-1.0-aws.jar

functions:
  main:
    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
    role: mainIamRole
    events:
      - s3: 
          bucket: ${self:custom.imagesS3Bucket}
          event: s3:ObjectCreated:*
          rules:
          - prefix: uploads/
    environment:
      S3_REGION: ${self:provider.region}
      S3_BUCKET_NAME: ${self:custom.imagesS3Bucket}

resources:
  - ${file(./cloudformation/iam/roles.yml)}