# Workflow for building and testing the application.
name: build-and-test

# Triggers the workflow on push or pull request events but only for the "main" branch.
on:
  workflow_call:
    inputs:
      ARTIFACT_NAME:
        type: string
        required: true

# This workflow contains "build" and "test" jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3

      # Setup Java JDK
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          distribution: "corretto"
          java-version: "17"

      # Build application
      - name: Build application
        run: |
          chmod 777 ./mvnw
          ./mvnw clean package

      - name: Upload app artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.ARTIFACT_NAME }}
          path: thumbnail-generator-1.0-aws.jar
