# Workflow for main pipeline.
name: main

# Triggers the workflow on push or pull request events but only for the "main" branch.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  call-workflow-build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with: 
      ARTIFACT_NAME: built-artifact
      
  call-workflow-release:
    needs: call-workflow-build-and-test
    uses: ./.github/workflows/release.yml
    with: 
      ARTIFACT_NAME: built-artifact
      AWS_REGION: us-east-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}