# Workflow for releasing the application.to AWS Cloud
name: release

on:
  workflow_call:
    inputs:
      AWS_REGION:
        type: string
        default: 'us-east-1'
      ARTIFACT_NAME:
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID: 
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.ARTIFACT_NAME }}

      - name: Install Severless Framework
        run: |
          npm install -g serverless

      - name: Release application
        run: |
          serverless deploy --package my-artifacts